import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Profile from "@/components/Profile";
import { cn } from "@/lib/utils";
import Backgroud from "@/components/Backgroud";
const font = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Vraj - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn("bg-[hsl(240,5%,9.8%)]", font.className)}>
        <Backgroud />
        <Sidebar />
        <Profile />
        {children}
      </body>
    </html>
  );
}
